Vote 페이지에서 신규유저 <-> 기존유저 전환 기능 추가
Team-Panopticon/TBD-client pull request #91
Opened 2023-06-07 13:07 UTC by junsushin-dev

closes #76 

## Summary

- MeetingVote 페이지에서 UserList 클릭을 통해서 신규유저 <-> 기존유저 전환기능
  - 기존유저가 선택된 상태에서 유저 선택 시 토글되어 신규 유저로 전환
  - 기존유저로 전환 시 DB에 저장된 투표상태로 currentUserVotingSlots 초기화
  - 신규유저로 전환 시 currentUserVotingSlots를 빈 배열로 전환

2023-06-10 02:06 UTC, juyoungpark718 requested changes

2023-06-10 02:06 UTC, juyoungpark718 commented on src/pages/MeetingVote.tsx
> +      setCurrentUser(undefined);
준수님 요기 undefined로 바꾸고 나서 새로고침 하는 경우

localStorage에서 값 가져올 때 JSON.parse(undefined)가 실행되어서 에러가 나는거 같습니다!

2023-06-10 02:50 UTC, junsushin-dev commented on src/pages/MeetingVote.tsx
> +      setCurrentUser(undefined);
제보 감사합니다~! 체크해볼게요

2023-06-10 02:59 UTC, junsushin-dev commented on src/pages/MeetingVote.tsx
> +      setCurrentUser(undefined);
해결을 위해서 setCurrentUser(undefined)를 resetCurrentUser()로 변경했습니다~!

2023-06-14 11:37 UTC, juyoungpark718 approved these changes
LGTM 👍 👍

2023-06-17 01:56 UTC, saeeng approved these changes
LGTM

2023-06-17 02:35 UTC, EarlyHail approved these changes
확인했습니다~!

2023-06-17 02:47 UTC, merged